CPPFLAGS= -Wall -Wextra -pedantic -g -pthread

all:
	# Insert command to compile the code and generate executable
	g++ -std=c++11 SharedPtr.hpp
	g++ -std=c++11 SharedPtr_test.cpp -o sharedptr
run:
	# Insert command to run the executable

checkmem:
	# Insert command to run the executable with valgrind

clean:
	# Insert command to clean object files, executables
